// Code generated by ziti-ci. DO NOT EDIT.

package sdkinfo

const (
	Version   = "v0.11.2"
	Revision  = "6a8aec738f97"
	Branch    = "master"
	BuildUser = "Travis CI User"
	BuildDate = "2020-03-19 20:58:49"
)
