// Code generated by ziti-ci. DO NOT EDIT.

package sdkinfo

const (
	Version   = "v0.13.9"
	Revision  = "3213ff2c9f89"
	Branch    = "master"
	BuildUser = "Travis CI User"
	BuildDate = "2020-06-18 20:49:28"
)
