// Code generated by ziti-ci. DO NOT EDIT.

package sdkinfo

const (
	Version   = "v0.12.2"
	Revision  = "5564d3685c97"
	Branch    = "master"
	BuildUser = "Travis CI User"
	BuildDate = "2020-06-10 15:08:41"
)
