// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: edge_client.proto

package edge_client_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentType int32

const (
	ContentType_Hello   ContentType = 0
	ContentType_Ping    ContentType = 1
	ContentType_Result  ContentType = 2
	ContentType_Latency ContentType = 3
	// use the same types as xgress uses on links
	ContentType_XgPayloadType                   ContentType = 1100
	ContentType_XgAcknowledgementType           ContentType = 1101
	ContentType_XgControlType                   ContentType = 1102
	ContentType_XgCloseType                     ContentType = 1103
	ContentType_ConnectType                     ContentType = 60783
	ContentType_StateConnectedType              ContentType = 60784
	ContentType_StateClosedType                 ContentType = 60785
	ContentType_DataType                        ContentType = 60786
	ContentType_DialType                        ContentType = 60787
	ContentType_DialSuccessType                 ContentType = 60788
	ContentType_DialFailedType                  ContentType = 60789
	ContentType_BindType                        ContentType = 60790
	ContentType_UnbindType                      ContentType = 60791
	ContentType_StateSessionEndedType           ContentType = 60792
	ContentType_ProbeType                       ContentType = 60793
	ContentType_UpdateBindType                  ContentType = 60794
	ContentType_HealthEventType                 ContentType = 60795
	ContentType_TraceRouteType                  ContentType = 60796
	ContentType_TraceRouteResponseType          ContentType = 60797
	ContentType_ConnInspectRequest              ContentType = 60798
	ContentType_ConnInspectResponse             ContentType = 60799
	ContentType_BindSuccess                     ContentType = 60800
	ContentType_UpdateTokenSuccessType          ContentType = 60801
	ContentType_UpdateTokenFailureType          ContentType = 60802
	ContentType_UpdateTokenType                 ContentType = 60803
	ContentType_InspectRequest                  ContentType = 60804
	ContentType_InspectResponse                 ContentType = 60805
	ContentType_ConnectV2Type                   ContentType = 60806
	ContentType_RouteCircuitType                ContentType = 60807
	ContentType_PostureResponseType             ContentType = 10800
	ContentType_ServicePostureStateRequestType  ContentType = 108001
	ContentType_ServicePostureStateResponseType ContentType = 108002
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0:      "Hello",
		1:      "Ping",
		2:      "Result",
		3:      "Latency",
		1100:   "XgPayloadType",
		1101:   "XgAcknowledgementType",
		1102:   "XgControlType",
		1103:   "XgCloseType",
		60783:  "ConnectType",
		60784:  "StateConnectedType",
		60785:  "StateClosedType",
		60786:  "DataType",
		60787:  "DialType",
		60788:  "DialSuccessType",
		60789:  "DialFailedType",
		60790:  "BindType",
		60791:  "UnbindType",
		60792:  "StateSessionEndedType",
		60793:  "ProbeType",
		60794:  "UpdateBindType",
		60795:  "HealthEventType",
		60796:  "TraceRouteType",
		60797:  "TraceRouteResponseType",
		60798:  "ConnInspectRequest",
		60799:  "ConnInspectResponse",
		60800:  "BindSuccess",
		60801:  "UpdateTokenSuccessType",
		60802:  "UpdateTokenFailureType",
		60803:  "UpdateTokenType",
		60804:  "InspectRequest",
		60805:  "InspectResponse",
		60806:  "ConnectV2Type",
		60807:  "RouteCircuitType",
		10800:  "PostureResponseType",
		108001: "ServicePostureStateRequestType",
		108002: "ServicePostureStateResponseType",
	}
	ContentType_value = map[string]int32{
		"Hello":                           0,
		"Ping":                            1,
		"Result":                          2,
		"Latency":                         3,
		"XgPayloadType":                   1100,
		"XgAcknowledgementType":           1101,
		"XgControlType":                   1102,
		"XgCloseType":                     1103,
		"ConnectType":                     60783,
		"StateConnectedType":              60784,
		"StateClosedType":                 60785,
		"DataType":                        60786,
		"DialType":                        60787,
		"DialSuccessType":                 60788,
		"DialFailedType":                  60789,
		"BindType":                        60790,
		"UnbindType":                      60791,
		"StateSessionEndedType":           60792,
		"ProbeType":                       60793,
		"UpdateBindType":                  60794,
		"HealthEventType":                 60795,
		"TraceRouteType":                  60796,
		"TraceRouteResponseType":          60797,
		"ConnInspectRequest":              60798,
		"ConnInspectResponse":             60799,
		"BindSuccess":                     60800,
		"UpdateTokenSuccessType":          60801,
		"UpdateTokenFailureType":          60802,
		"UpdateTokenType":                 60803,
		"InspectRequest":                  60804,
		"InspectResponse":                 60805,
		"ConnectV2Type":                   60806,
		"RouteCircuitType":                60807,
		"PostureResponseType":             10800,
		"ServicePostureStateRequestType":  108001,
		"ServicePostureStateResponseType": 108002,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_edge_client_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_edge_client_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{0}
}

type HeaderId int32

const (
	HeaderId_ZER0                     HeaderId = 0
	HeaderId_UUID                     HeaderId = 128
	HeaderId_ConnId                   HeaderId = 1000
	HeaderId_Seq                      HeaderId = 1001
	HeaderId_SessionToken             HeaderId = 1002
	HeaderId_PublicKey                HeaderId = 1003
	HeaderId_Cost                     HeaderId = 1004
	HeaderId_Precedence               HeaderId = 1005
	HeaderId_TerminatorIdentity       HeaderId = 1006
	HeaderId_TerminatorIdentitySecret HeaderId = 1007
	HeaderId_CallerId                 HeaderId = 1008
	HeaderId_CryptoMethod             HeaderId = 1009
	HeaderId_Flags                    HeaderId = 1010
	HeaderId_AppData                  HeaderId = 1011
	HeaderId_RouterProvidedConnId     HeaderId = 1012
	HeaderId_HealthStatus             HeaderId = 1013
	HeaderId_ErrorCode                HeaderId = 1014
	HeaderId_Timestamp                HeaderId = 1015
	HeaderId_TraceHopCount            HeaderId = 1016
	HeaderId_TraceHopType             HeaderId = 1017
	HeaderId_TraceHopId               HeaderId = 1018
	HeaderId_TraceSourceRequestId     HeaderId = 1019
	HeaderId_TraceError               HeaderId = 1020
	HeaderId_ListenerId               HeaderId = 1021
	HeaderId_ConnType                 HeaderId = 1022
	HeaderId_SupportsInspect          HeaderId = 1023
	HeaderId_SupportsBindSuccess      HeaderId = 1024
	HeaderId_ConnectionMarker         HeaderId = 1025
	HeaderId_CircuitId                HeaderId = 1026
	HeaderId_StickinessToken          HeaderId = 1027
	HeaderId_UseXgressToSdk           HeaderId = 1028
	HeaderId_XgressCtrlId             HeaderId = 1029
	HeaderId_XgressAddress            HeaderId = 1030
	HeaderId_InspectRequestedValues   HeaderId = 1031
	HeaderId_SupportsPostureChecks    HeaderId = 1032
	HeaderId_StructuredError          HeaderId = 1033
	HeaderId_DialerIdentityId         HeaderId = 1034
	HeaderId_DialerIdentityName       HeaderId = 1035
	HeaderId_ServiceId                HeaderId = 1036
	HeaderId_ServiceIdentifierType    HeaderId = 1037
	HeaderId_ConnectRequestId         HeaderId = 1038
	HeaderId_RouterCapabilities       HeaderId = 1039
)

// Enum value maps for HeaderId.
var (
	HeaderId_name = map[int32]string{
		0:    "ZER0",
		128:  "UUID",
		1000: "ConnId",
		1001: "Seq",
		1002: "SessionToken",
		1003: "PublicKey",
		1004: "Cost",
		1005: "Precedence",
		1006: "TerminatorIdentity",
		1007: "TerminatorIdentitySecret",
		1008: "CallerId",
		1009: "CryptoMethod",
		1010: "Flags",
		1011: "AppData",
		1012: "RouterProvidedConnId",
		1013: "HealthStatus",
		1014: "ErrorCode",
		1015: "Timestamp",
		1016: "TraceHopCount",
		1017: "TraceHopType",
		1018: "TraceHopId",
		1019: "TraceSourceRequestId",
		1020: "TraceError",
		1021: "ListenerId",
		1022: "ConnType",
		1023: "SupportsInspect",
		1024: "SupportsBindSuccess",
		1025: "ConnectionMarker",
		1026: "CircuitId",
		1027: "StickinessToken",
		1028: "UseXgressToSdk",
		1029: "XgressCtrlId",
		1030: "XgressAddress",
		1031: "InspectRequestedValues",
		1032: "SupportsPostureChecks",
		1033: "StructuredError",
		1034: "DialerIdentityId",
		1035: "DialerIdentityName",
		1036: "ServiceId",
		1037: "ServiceIdentifierType",
		1038: "ConnectRequestId",
		1039: "RouterCapabilities",
	}
	HeaderId_value = map[string]int32{
		"ZER0":                     0,
		"UUID":                     128,
		"ConnId":                   1000,
		"Seq":                      1001,
		"SessionToken":             1002,
		"PublicKey":                1003,
		"Cost":                     1004,
		"Precedence":               1005,
		"TerminatorIdentity":       1006,
		"TerminatorIdentitySecret": 1007,
		"CallerId":                 1008,
		"CryptoMethod":             1009,
		"Flags":                    1010,
		"AppData":                  1011,
		"RouterProvidedConnId":     1012,
		"HealthStatus":             1013,
		"ErrorCode":                1014,
		"Timestamp":                1015,
		"TraceHopCount":            1016,
		"TraceHopType":             1017,
		"TraceHopId":               1018,
		"TraceSourceRequestId":     1019,
		"TraceError":               1020,
		"ListenerId":               1021,
		"ConnType":                 1022,
		"SupportsInspect":          1023,
		"SupportsBindSuccess":      1024,
		"ConnectionMarker":         1025,
		"CircuitId":                1026,
		"StickinessToken":          1027,
		"UseXgressToSdk":           1028,
		"XgressCtrlId":             1029,
		"XgressAddress":            1030,
		"InspectRequestedValues":   1031,
		"SupportsPostureChecks":    1032,
		"StructuredError":          1033,
		"DialerIdentityId":         1034,
		"DialerIdentityName":       1035,
		"ServiceId":                1036,
		"ServiceIdentifierType":    1037,
		"ConnectRequestId":         1038,
		"RouterCapabilities":       1039,
	}
)

func (x HeaderId) Enum() *HeaderId {
	p := new(HeaderId)
	*p = x
	return p
}

func (x HeaderId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeaderId) Descriptor() protoreflect.EnumDescriptor {
	return file_edge_client_proto_enumTypes[1].Descriptor()
}

func (HeaderId) Type() protoreflect.EnumType {
	return &file_edge_client_proto_enumTypes[1]
}

func (x HeaderId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeaderId.Descriptor instead.
func (HeaderId) EnumDescriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{1}
}

type Error int32

const (
	Error_OK                          Error = 0
	Error_Internal                    Error = 1
	Error_InvalidApiSession           Error = 2
	Error_InvalidSession              Error = 3
	Error_WrongSessionType            Error = 4
	Error_InvalidEdgeRouterForSession Error = 5
	Error_InvalidService              Error = 6
	Error_TunnelingNotEnabled         Error = 7
	Error_InvalidTerminator           Error = 8
	Error_InvalidPrecedence           Error = 9
	Error_InvalidCost                 Error = 10
	Error_EncryptionDataMissing       Error = 11
	Error_InvalidApiSessionType       Error = 12
	Error_InvalidInstanceId           Error = 13
	Error_AccessDenied                Error = 14
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0:  "OK",
		1:  "Internal",
		2:  "InvalidApiSession",
		3:  "InvalidSession",
		4:  "WrongSessionType",
		5:  "InvalidEdgeRouterForSession",
		6:  "InvalidService",
		7:  "TunnelingNotEnabled",
		8:  "InvalidTerminator",
		9:  "InvalidPrecedence",
		10: "InvalidCost",
		11: "EncryptionDataMissing",
		12: "InvalidApiSessionType",
		13: "InvalidInstanceId",
		14: "AccessDenied",
	}
	Error_value = map[string]int32{
		"OK":                          0,
		"Internal":                    1,
		"InvalidApiSession":           2,
		"InvalidSession":              3,
		"WrongSessionType":            4,
		"InvalidEdgeRouterForSession": 5,
		"InvalidService":              6,
		"TunnelingNotEnabled":         7,
		"InvalidTerminator":           8,
		"InvalidPrecedence":           9,
		"InvalidCost":                 10,
		"EncryptionDataMissing":       11,
		"InvalidApiSessionType":       12,
		"InvalidInstanceId":           13,
		"AccessDenied":                14,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_edge_client_proto_enumTypes[2].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_edge_client_proto_enumTypes[2]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{2}
}

type PrecedenceValue int32

const (
	PrecedenceValue_Default  PrecedenceValue = 0
	PrecedenceValue_Required PrecedenceValue = 1
	PrecedenceValue_Failed   PrecedenceValue = 2
)

// Enum value maps for PrecedenceValue.
var (
	PrecedenceValue_name = map[int32]string{
		0: "Default",
		1: "Required",
		2: "Failed",
	}
	PrecedenceValue_value = map[string]int32{
		"Default":  0,
		"Required": 1,
		"Failed":   2,
	}
)

func (x PrecedenceValue) Enum() *PrecedenceValue {
	p := new(PrecedenceValue)
	*p = x
	return p
}

func (x PrecedenceValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrecedenceValue) Descriptor() protoreflect.EnumDescriptor {
	return file_edge_client_proto_enumTypes[3].Descriptor()
}

func (PrecedenceValue) Type() protoreflect.EnumType {
	return &file_edge_client_proto_enumTypes[3]
}

func (x PrecedenceValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrecedenceValue.Descriptor instead.
func (PrecedenceValue) EnumDescriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{3}
}

type Flag int32

const (
	Flag_ZERO Flag = 0
	// FIN is an edge payload flag used to signal communication ends
	Flag_FIN Flag = 1
	// TRACE_UUID indicates that peer will send data messages with specially constructed UUID headers
	Flag_TRACE_UUID Flag = 2
	// MULTIPART indicates that peer can accept multipart data messages
	Flag_MULTIPART Flag = 4
	// STREAM indicates connection with stream semantics
	// this allows consolidation of payloads to lower overhead
	Flag_STREAM Flag = 8
	// MULTIPART_MSG set on data message with multiple payloads
	Flag_MULTIPART_MSG Flag = 16
)

// Enum value maps for Flag.
var (
	Flag_name = map[int32]string{
		0:  "ZERO",
		1:  "FIN",
		2:  "TRACE_UUID",
		4:  "MULTIPART",
		8:  "STREAM",
		16: "MULTIPART_MSG",
	}
	Flag_value = map[string]int32{
		"ZERO":          0,
		"FIN":           1,
		"TRACE_UUID":    2,
		"MULTIPART":     4,
		"STREAM":        8,
		"MULTIPART_MSG": 16,
	}
)

func (x Flag) Enum() *Flag {
	p := new(Flag)
	*p = x
	return p
}

func (x Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_edge_client_proto_enumTypes[4].Descriptor()
}

func (Flag) Type() protoreflect.EnumType {
	return &file_edge_client_proto_enumTypes[4]
}

func (x Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Flag.Descriptor instead.
func (Flag) EnumDescriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{4}
}

type ServicePostureStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceIds    []string               `protobuf:"bytes,1,rep,name=serviceIds,proto3" json:"serviceIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePostureStateRequest) Reset() {
	*x = ServicePostureStateRequest{}
	mi := &file_edge_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePostureStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePostureStateRequest) ProtoMessage() {}

func (x *ServicePostureStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePostureStateRequest.ProtoReflect.Descriptor instead.
func (*ServicePostureStateRequest) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{0}
}

func (x *ServicePostureStateRequest) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

type ServicePostureStateResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	States        map[string]*ServicePostureState `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePostureStateResponse) Reset() {
	*x = ServicePostureStateResponse{}
	mi := &file_edge_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePostureStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePostureStateResponse) ProtoMessage() {}

func (x *ServicePostureStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePostureStateResponse.ProtoReflect.Descriptor instead.
func (*ServicePostureStateResponse) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{1}
}

func (x *ServicePostureStateResponse) GetStates() map[string]*ServicePostureState {
	if x != nil {
		return x.States
	}
	return nil
}

type ServicePostureState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsPassing        bool                   `protobuf:"varint,1,opt,name=isPassing,proto3" json:"isPassing,omitempty"`
	PassingPolicyIds []string               `protobuf:"bytes,2,rep,name=passingPolicyIds,proto3" json:"passingPolicyIds,omitempty"`
	FailingPolicyIds []string               `protobuf:"bytes,3,rep,name=failingPolicyIds,proto3" json:"failingPolicyIds,omitempty"`
	Policies         map[string]*Policy     `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServicePostureState) Reset() {
	*x = ServicePostureState{}
	mi := &file_edge_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePostureState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePostureState) ProtoMessage() {}

func (x *ServicePostureState) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePostureState.ProtoReflect.Descriptor instead.
func (*ServicePostureState) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{2}
}

func (x *ServicePostureState) GetIsPassing() bool {
	if x != nil {
		return x.IsPassing
	}
	return false
}

func (x *ServicePostureState) GetPassingPolicyIds() []string {
	if x != nil {
		return x.PassingPolicyIds
	}
	return nil
}

func (x *ServicePostureState) GetFailingPolicyIds() []string {
	if x != nil {
		return x.FailingPolicyIds
	}
	return nil
}

func (x *ServicePostureState) GetPolicies() map[string]*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type Policy struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Id                     string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsPassing              bool                     `protobuf:"varint,2,opt,name=isPassing,proto3" json:"isPassing,omitempty"`
	PassingPostureQueryIds []string                 `protobuf:"bytes,3,rep,name=passingPostureQueryIds,proto3" json:"passingPostureQueryIds,omitempty"`
	FailingPostureQueryIds []string                 `protobuf:"bytes,4,rep,name=failingPostureQueryIds,proto3" json:"failingPostureQueryIds,omitempty"`
	PostureQueries         map[string]*PostureQuery `protobuf:"bytes,5,rep,name=postureQueries,proto3" json:"postureQueries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_edge_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{3}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetIsPassing() bool {
	if x != nil {
		return x.IsPassing
	}
	return false
}

func (x *Policy) GetPassingPostureQueryIds() []string {
	if x != nil {
		return x.PassingPostureQueryIds
	}
	return nil
}

func (x *Policy) GetFailingPostureQueryIds() []string {
	if x != nil {
		return x.FailingPostureQueryIds
	}
	return nil
}

func (x *Policy) GetPostureQueries() map[string]*PostureQuery {
	if x != nil {
		return x.PostureQueries
	}
	return nil
}

type PostureQuery struct {
	state                    protoimpl.MessageState  `protogen:"open.v1"`
	Id                       string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                     string                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsPassing                bool                    `protobuf:"varint,3,opt,name=isPassing,proto3" json:"isPassing,omitempty"`
	TimeoutAt                *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=timeoutAt,proto3" json:"timeoutAt,omitempty"`
	TimeoutSeconds           int32                   `protobuf:"varint,5,opt,name=timeoutSeconds,proto3" json:"timeoutSeconds,omitempty"`
	TimeoutRemainingSeconds  int32                   `protobuf:"varint,6,opt,name=timeoutRemainingSeconds,proto3" json:"timeoutRemainingSeconds,omitempty"`
	PromptGracePeriodSeconds int32                   `protobuf:"varint,7,opt,name=promptGracePeriodSeconds,proto3" json:"promptGracePeriodSeconds,omitempty"`
	PromptOnUnlock           bool                    `protobuf:"varint,8,opt,name=promptOnUnlock,proto3" json:"promptOnUnlock,omitempty"`
	PromptOnWake             bool                    `protobuf:"varint,9,opt,name=promptOnWake,proto3" json:"promptOnWake,omitempty"`
	Processes                *PostureQuery_Processes `protobuf:"bytes,10,opt,name=processes,proto3" json:"processes,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PostureQuery) Reset() {
	*x = PostureQuery{}
	mi := &file_edge_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureQuery) ProtoMessage() {}

func (x *PostureQuery) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureQuery.ProtoReflect.Descriptor instead.
func (*PostureQuery) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{4}
}

func (x *PostureQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostureQuery) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PostureQuery) GetIsPassing() bool {
	if x != nil {
		return x.IsPassing
	}
	return false
}

func (x *PostureQuery) GetTimeoutAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeoutAt
	}
	return nil
}

func (x *PostureQuery) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *PostureQuery) GetTimeoutRemainingSeconds() int32 {
	if x != nil {
		return x.TimeoutRemainingSeconds
	}
	return 0
}

func (x *PostureQuery) GetPromptGracePeriodSeconds() int32 {
	if x != nil {
		return x.PromptGracePeriodSeconds
	}
	return 0
}

func (x *PostureQuery) GetPromptOnUnlock() bool {
	if x != nil {
		return x.PromptOnUnlock
	}
	return false
}

func (x *PostureQuery) GetPromptOnWake() bool {
	if x != nil {
		return x.PromptOnWake
	}
	return false
}

func (x *PostureQuery) GetProcesses() *PostureQuery_Processes {
	if x != nil {
		return x.Processes
	}
	return nil
}

type PostureResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*PostureResponse     `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponses) Reset() {
	*x = PostureResponses{}
	mi := &file_edge_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponses) ProtoMessage() {}

func (x *PostureResponses) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponses.ProtoReflect.Descriptor instead.
func (*PostureResponses) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{5}
}

func (x *PostureResponses) GetResponses() []*PostureResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type PostureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*PostureResponse_Macs_
	//	*PostureResponse_Os
	//	*PostureResponse_ProcessList_
	//	*PostureResponse_Domain_
	//	*PostureResponse_Woken_
	//	*PostureResponse_Unlocked_
	//	*PostureResponse_SdkInfo_
	//	*PostureResponse_TotpToken_
	Type          isPostureResponse_Type `protobuf_oneof:"Type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse) Reset() {
	*x = PostureResponse{}
	mi := &file_edge_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse) ProtoMessage() {}

func (x *PostureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse.ProtoReflect.Descriptor instead.
func (*PostureResponse) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6}
}

func (x *PostureResponse) GetType() isPostureResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PostureResponse) GetMacs() *PostureResponse_Macs {
	if x != nil {
		if x, ok := x.Type.(*PostureResponse_Macs_); ok {
			return x.Macs
		}
	}
	return nil
}

func (x *PostureResponse) GetOs() *PostureResponse_OperatingSystem {
	if x != nil {
		if x, ok := x.Type.(*PostureResponse_Os); ok {
			return x.Os
		}
	}
	return nil
}

func (x *PostureResponse) GetProcessList() *PostureResponse_ProcessList {
	if x != nil {
		if x, ok := x.Type.(*PostureResponse_ProcessList_); ok {
			return x.ProcessList
		}
	}
	return nil
}

func (x *PostureResponse) GetDomain() *PostureResponse_Domain {
	if x != nil {
		if x, ok := x.Type.(*PostureResponse_Domain_); ok {
			return x.Domain
		}
	}
	return nil
}

func (x *PostureResponse) GetWoken() *PostureResponse_Woken {
	if x != nil {
		if x, ok := x.Type.(*PostureResponse_Woken_); ok {
			return x.Woken
		}
	}
	return nil
}

func (x *PostureResponse) GetUnlocked() *PostureResponse_Unlocked {
	if x != nil {
		if x, ok := x.Type.(*PostureResponse_Unlocked_); ok {
			return x.Unlocked
		}
	}
	return nil
}

func (x *PostureResponse) GetSdkInfo() *PostureResponse_SdkInfo {
	if x != nil {
		if x, ok := x.Type.(*PostureResponse_SdkInfo_); ok {
			return x.SdkInfo
		}
	}
	return nil
}

func (x *PostureResponse) GetTotpToken() *PostureResponse_TotpToken {
	if x != nil {
		if x, ok := x.Type.(*PostureResponse_TotpToken_); ok {
			return x.TotpToken
		}
	}
	return nil
}

type isPostureResponse_Type interface {
	isPostureResponse_Type()
}

type PostureResponse_Macs_ struct {
	Macs *PostureResponse_Macs `protobuf:"bytes,1,opt,name=macs,proto3,oneof"`
}

type PostureResponse_Os struct {
	Os *PostureResponse_OperatingSystem `protobuf:"bytes,2,opt,name=os,proto3,oneof"`
}

type PostureResponse_ProcessList_ struct {
	ProcessList *PostureResponse_ProcessList `protobuf:"bytes,3,opt,name=processList,proto3,oneof"`
}

type PostureResponse_Domain_ struct {
	Domain *PostureResponse_Domain `protobuf:"bytes,4,opt,name=domain,proto3,oneof"`
}

type PostureResponse_Woken_ struct {
	Woken *PostureResponse_Woken `protobuf:"bytes,5,opt,name=woken,proto3,oneof"`
}

type PostureResponse_Unlocked_ struct {
	Unlocked *PostureResponse_Unlocked `protobuf:"bytes,6,opt,name=unlocked,proto3,oneof"`
}

type PostureResponse_SdkInfo_ struct {
	SdkInfo *PostureResponse_SdkInfo `protobuf:"bytes,7,opt,name=sdkInfo,proto3,oneof"`
}

type PostureResponse_TotpToken_ struct {
	TotpToken *PostureResponse_TotpToken `protobuf:"bytes,8,opt,name=totpToken,proto3,oneof"`
}

func (*PostureResponse_Macs_) isPostureResponse_Type() {}

func (*PostureResponse_Os) isPostureResponse_Type() {}

func (*PostureResponse_ProcessList_) isPostureResponse_Type() {}

func (*PostureResponse_Domain_) isPostureResponse_Type() {}

func (*PostureResponse_Woken_) isPostureResponse_Type() {}

func (*PostureResponse_Unlocked_) isPostureResponse_Type() {}

func (*PostureResponse_SdkInfo_) isPostureResponse_Type() {}

func (*PostureResponse_TotpToken_) isPostureResponse_Type() {}

type PostureQuery_Processes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Semantic      string                  `protobuf:"bytes,1,opt,name=semantic,proto3" json:"semantic,omitempty"`
	Processes     []*PostureQuery_Process `protobuf:"bytes,2,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureQuery_Processes) Reset() {
	*x = PostureQuery_Processes{}
	mi := &file_edge_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureQuery_Processes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureQuery_Processes) ProtoMessage() {}

func (x *PostureQuery_Processes) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureQuery_Processes.ProtoReflect.Descriptor instead.
func (*PostureQuery_Processes) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PostureQuery_Processes) GetSemantic() string {
	if x != nil {
		return x.Semantic
	}
	return ""
}

func (x *PostureQuery_Processes) GetProcesses() []*PostureQuery_Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

type PostureQuery_Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OsType        string                 `protobuf:"bytes,1,opt,name=osType,proto3" json:"osType,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureQuery_Process) Reset() {
	*x = PostureQuery_Process{}
	mi := &file_edge_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureQuery_Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureQuery_Process) ProtoMessage() {}

func (x *PostureQuery_Process) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureQuery_Process.ProtoReflect.Descriptor instead.
func (*PostureQuery_Process) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{4, 1}
}

func (x *PostureQuery_Process) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *PostureQuery_Process) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PostureResponse_TotpToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse_TotpToken) Reset() {
	*x = PostureResponse_TotpToken{}
	mi := &file_edge_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_TotpToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_TotpToken) ProtoMessage() {}

func (x *PostureResponse_TotpToken) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_TotpToken.ProtoReflect.Descriptor instead.
func (*PostureResponse_TotpToken) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 0}
}

func (x *PostureResponse_TotpToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PostureResponse_TotpToken) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PostureResponse_Macs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse_Macs) Reset() {
	*x = PostureResponse_Macs{}
	mi := &file_edge_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_Macs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_Macs) ProtoMessage() {}

func (x *PostureResponse_Macs) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_Macs.ProtoReflect.Descriptor instead.
func (*PostureResponse_Macs) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 1}
}

func (x *PostureResponse_Macs) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type PostureResponse_OperatingSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Build         string                 `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse_OperatingSystem) Reset() {
	*x = PostureResponse_OperatingSystem{}
	mi := &file_edge_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_OperatingSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_OperatingSystem) ProtoMessage() {}

func (x *PostureResponse_OperatingSystem) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_OperatingSystem.ProtoReflect.Descriptor instead.
func (*PostureResponse_OperatingSystem) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 2}
}

func (x *PostureResponse_OperatingSystem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PostureResponse_OperatingSystem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PostureResponse_OperatingSystem) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

type PostureResponse_Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse_Domain) Reset() {
	*x = PostureResponse_Domain{}
	mi := &file_edge_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_Domain) ProtoMessage() {}

func (x *PostureResponse_Domain) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_Domain.ProtoReflect.Descriptor instead.
func (*PostureResponse_Domain) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 3}
}

func (x *PostureResponse_Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostureResponse_Process struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Path               string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsRunning          bool                   `protobuf:"varint,2,opt,name=isRunning,proto3" json:"isRunning,omitempty"`
	Hash               string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	SignerFingerprints []string               `protobuf:"bytes,4,rep,name=signerFingerprints,proto3" json:"signerFingerprints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PostureResponse_Process) Reset() {
	*x = PostureResponse_Process{}
	mi := &file_edge_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_Process) ProtoMessage() {}

func (x *PostureResponse_Process) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_Process.ProtoReflect.Descriptor instead.
func (*PostureResponse_Process) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 4}
}

func (x *PostureResponse_Process) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PostureResponse_Process) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *PostureResponse_Process) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PostureResponse_Process) GetSignerFingerprints() []string {
	if x != nil {
		return x.SignerFingerprints
	}
	return nil
}

type PostureResponse_ProcessList struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Processes     []*PostureResponse_Process `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse_ProcessList) Reset() {
	*x = PostureResponse_ProcessList{}
	mi := &file_edge_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_ProcessList) ProtoMessage() {}

func (x *PostureResponse_ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_ProcessList.ProtoReflect.Descriptor instead.
func (*PostureResponse_ProcessList) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 5}
}

func (x *PostureResponse_ProcessList) GetProcesses() []*PostureResponse_Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

type PostureResponse_Woken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse_Woken) Reset() {
	*x = PostureResponse_Woken{}
	mi := &file_edge_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_Woken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_Woken) ProtoMessage() {}

func (x *PostureResponse_Woken) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_Woken.ProtoReflect.Descriptor instead.
func (*PostureResponse_Woken) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 6}
}

func (x *PostureResponse_Woken) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type PostureResponse_Unlocked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse_Unlocked) Reset() {
	*x = PostureResponse_Unlocked{}
	mi := &file_edge_client_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_Unlocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_Unlocked) ProtoMessage() {}

func (x *PostureResponse_Unlocked) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_Unlocked.ProtoReflect.Descriptor instead.
func (*PostureResponse_Unlocked) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 7}
}

func (x *PostureResponse_Unlocked) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type PostureResponse_SdkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppVersion    string                 `protobuf:"bytes,2,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Revision      string                 `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostureResponse_SdkInfo) Reset() {
	*x = PostureResponse_SdkInfo{}
	mi := &file_edge_client_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostureResponse_SdkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostureResponse_SdkInfo) ProtoMessage() {}

func (x *PostureResponse_SdkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_edge_client_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostureResponse_SdkInfo.ProtoReflect.Descriptor instead.
func (*PostureResponse_SdkInfo) Descriptor() ([]byte, []int) {
	return file_edge_client_proto_rawDescGZIP(), []int{6, 8}
}

func (x *PostureResponse_SdkInfo) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PostureResponse_SdkInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *PostureResponse_SdkInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PostureResponse_SdkInfo) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *PostureResponse_SdkInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PostureResponse_SdkInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_edge_client_proto protoreflect.FileDescriptor

const file_edge_client_proto_rawDesc = "" +
	"\n" +
	"\x11edge_client.proto\x12\x13ziti.edge_client.pb\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x1aServicePostureStateRequest\x12\x1e\n" +
	"\n" +
	"serviceIds\x18\x01 \x03(\tR\n" +
	"serviceIds\"\xd8\x01\n" +
	"\x1bServicePostureStateResponse\x12T\n" +
	"\x06states\x18\x01 \x03(\v2<.ziti.edge_client.pb.ServicePostureStateResponse.StatesEntryR\x06states\x1ac\n" +
	"\vStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.ziti.edge_client.pb.ServicePostureStateR\x05value:\x028\x01\"\xb9\x02\n" +
	"\x13ServicePostureState\x12\x1c\n" +
	"\tisPassing\x18\x01 \x01(\bR\tisPassing\x12*\n" +
	"\x10passingPolicyIds\x18\x02 \x03(\tR\x10passingPolicyIds\x12*\n" +
	"\x10failingPolicyIds\x18\x03 \x03(\tR\x10failingPolicyIds\x12R\n" +
	"\bpolicies\x18\x04 \x03(\v26.ziti.edge_client.pb.ServicePostureState.PoliciesEntryR\bpolicies\x1aX\n" +
	"\rPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.ziti.edge_client.pb.PolicyR\x05value:\x028\x01\"\xe5\x02\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tisPassing\x18\x02 \x01(\bR\tisPassing\x126\n" +
	"\x16passingPostureQueryIds\x18\x03 \x03(\tR\x16passingPostureQueryIds\x126\n" +
	"\x16failingPostureQueryIds\x18\x04 \x03(\tR\x16failingPostureQueryIds\x12W\n" +
	"\x0epostureQueries\x18\x05 \x03(\v2/.ziti.edge_client.pb.Policy.PostureQueriesEntryR\x0epostureQueries\x1ad\n" +
	"\x13PostureQueriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.ziti.edge_client.pb.PostureQueryR\x05value:\x028\x01\"\xe8\x04\n" +
	"\fPostureQuery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tisPassing\x18\x03 \x01(\bR\tisPassing\x128\n" +
	"\ttimeoutAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeoutAt\x12&\n" +
	"\x0etimeoutSeconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x128\n" +
	"\x17timeoutRemainingSeconds\x18\x06 \x01(\x05R\x17timeoutRemainingSeconds\x12:\n" +
	"\x18promptGracePeriodSeconds\x18\a \x01(\x05R\x18promptGracePeriodSeconds\x12&\n" +
	"\x0epromptOnUnlock\x18\b \x01(\bR\x0epromptOnUnlock\x12\"\n" +
	"\fpromptOnWake\x18\t \x01(\bR\fpromptOnWake\x12I\n" +
	"\tprocesses\x18\n" +
	" \x01(\v2+.ziti.edge_client.pb.PostureQuery.ProcessesR\tprocesses\x1ap\n" +
	"\tProcesses\x12\x1a\n" +
	"\bsemantic\x18\x01 \x01(\tR\bsemantic\x12G\n" +
	"\tprocesses\x18\x02 \x03(\v2).ziti.edge_client.pb.PostureQuery.ProcessR\tprocesses\x1a5\n" +
	"\aProcess\x12\x16\n" +
	"\x06osType\x18\x01 \x01(\tR\x06osType\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"V\n" +
	"\x10PostureResponses\x12B\n" +
	"\tresponses\x18\x01 \x03(\v2$.ziti.edge_client.pb.PostureResponseR\tresponses\"\xb1\n" +
	"\n" +
	"\x0fPostureResponse\x12?\n" +
	"\x04macs\x18\x01 \x01(\v2).ziti.edge_client.pb.PostureResponse.MacsH\x00R\x04macs\x12F\n" +
	"\x02os\x18\x02 \x01(\v24.ziti.edge_client.pb.PostureResponse.OperatingSystemH\x00R\x02os\x12T\n" +
	"\vprocessList\x18\x03 \x01(\v20.ziti.edge_client.pb.PostureResponse.ProcessListH\x00R\vprocessList\x12E\n" +
	"\x06domain\x18\x04 \x01(\v2+.ziti.edge_client.pb.PostureResponse.DomainH\x00R\x06domain\x12B\n" +
	"\x05woken\x18\x05 \x01(\v2*.ziti.edge_client.pb.PostureResponse.WokenH\x00R\x05woken\x12K\n" +
	"\bunlocked\x18\x06 \x01(\v2-.ziti.edge_client.pb.PostureResponse.UnlockedH\x00R\bunlocked\x12H\n" +
	"\asdkInfo\x18\a \x01(\v2,.ziti.edge_client.pb.PostureResponse.SdkInfoH\x00R\asdkInfo\x12N\n" +
	"\ttotpToken\x18\b \x01(\v2..ziti.edge_client.pb.PostureResponse.TotpTokenH\x00R\ttotpToken\x1a5\n" +
	"\tTotpToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x1a$\n" +
	"\x04Macs\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x1aU\n" +
	"\x0fOperatingSystem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05build\x18\x03 \x01(\tR\x05build\x1a\x1c\n" +
	"\x06Domain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a\x7f\n" +
	"\aProcess\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\tisRunning\x18\x02 \x01(\bR\tisRunning\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12.\n" +
	"\x12signerFingerprints\x18\x04 \x03(\tR\x12signerFingerprints\x1aY\n" +
	"\vProcessList\x12J\n" +
	"\tprocesses\x18\x01 \x03(\v2,.ziti.edge_client.pb.PostureResponse.ProcessR\tprocesses\x1a7\n" +
	"\x05Woken\x12.\n" +
	"\x04Time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04Time\x1a:\n" +
	"\bUnlocked\x12.\n" +
	"\x04Time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04Time\x1a\xa1\x01\n" +
	"\aSdkInfo\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x02 \x01(\tR\n" +
	"appVersion\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\tR\brevision\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversionB\x06\n" +
	"\x04Type*\xaf\x06\n" +
	"\vContentType\x12\t\n" +
	"\x05Hello\x10\x00\x12\b\n" +
	"\x04Ping\x10\x01\x12\n" +
	"\n" +
	"\x06Result\x10\x02\x12\v\n" +
	"\aLatency\x10\x03\x12\x12\n" +
	"\rXgPayloadType\x10\xcc\b\x12\x1a\n" +
	"\x15XgAcknowledgementType\x10\xcd\b\x12\x12\n" +
	"\rXgControlType\x10\xce\b\x12\x10\n" +
	"\vXgCloseType\x10\xcf\b\x12\x11\n" +
	"\vConnectType\x10\xef\xda\x03\x12\x18\n" +
	"\x12StateConnectedType\x10\xf0\xda\x03\x12\x15\n" +
	"\x0fStateClosedType\x10\xf1\xda\x03\x12\x0e\n" +
	"\bDataType\x10\xf2\xda\x03\x12\x0e\n" +
	"\bDialType\x10\xf3\xda\x03\x12\x15\n" +
	"\x0fDialSuccessType\x10\xf4\xda\x03\x12\x14\n" +
	"\x0eDialFailedType\x10\xf5\xda\x03\x12\x0e\n" +
	"\bBindType\x10\xf6\xda\x03\x12\x10\n" +
	"\n" +
	"UnbindType\x10\xf7\xda\x03\x12\x1b\n" +
	"\x15StateSessionEndedType\x10\xf8\xda\x03\x12\x0f\n" +
	"\tProbeType\x10\xf9\xda\x03\x12\x14\n" +
	"\x0eUpdateBindType\x10\xfa\xda\x03\x12\x15\n" +
	"\x0fHealthEventType\x10\xfb\xda\x03\x12\x14\n" +
	"\x0eTraceRouteType\x10\xfc\xda\x03\x12\x1c\n" +
	"\x16TraceRouteResponseType\x10\xfd\xda\x03\x12\x18\n" +
	"\x12ConnInspectRequest\x10\xfe\xda\x03\x12\x19\n" +
	"\x13ConnInspectResponse\x10\xff\xda\x03\x12\x11\n" +
	"\vBindSuccess\x10\x80\xdb\x03\x12\x1c\n" +
	"\x16UpdateTokenSuccessType\x10\x81\xdb\x03\x12\x1c\n" +
	"\x16UpdateTokenFailureType\x10\x82\xdb\x03\x12\x15\n" +
	"\x0fUpdateTokenType\x10\x83\xdb\x03\x12\x14\n" +
	"\x0eInspectRequest\x10\x84\xdb\x03\x12\x15\n" +
	"\x0fInspectResponse\x10\x85\xdb\x03\x12\x13\n" +
	"\rConnectV2Type\x10\x86\xdb\x03\x12\x16\n" +
	"\x10RouteCircuitType\x10\x87\xdb\x03\x12\x18\n" +
	"\x13PostureResponseType\x10\xb0T\x12$\n" +
	"\x1eServicePostureStateRequestType\x10\xe1\xcb\x06\x12%\n" +
	"\x1fServicePostureStateResponseType\x10\xe2\xcb\x06*\xbf\x06\n" +
	"\bHeaderId\x12\b\n" +
	"\x04ZER0\x10\x00\x12\t\n" +
	"\x04UUID\x10\x80\x01\x12\v\n" +
	"\x06ConnId\x10\xe8\a\x12\b\n" +
	"\x03Seq\x10\xe9\a\x12\x11\n" +
	"\fSessionToken\x10\xea\a\x12\x0e\n" +
	"\tPublicKey\x10\xeb\a\x12\t\n" +
	"\x04Cost\x10\xec\a\x12\x0f\n" +
	"\n" +
	"Precedence\x10\xed\a\x12\x17\n" +
	"\x12TerminatorIdentity\x10\xee\a\x12\x1d\n" +
	"\x18TerminatorIdentitySecret\x10\xef\a\x12\r\n" +
	"\bCallerId\x10\xf0\a\x12\x11\n" +
	"\fCryptoMethod\x10\xf1\a\x12\n" +
	"\n" +
	"\x05Flags\x10\xf2\a\x12\f\n" +
	"\aAppData\x10\xf3\a\x12\x19\n" +
	"\x14RouterProvidedConnId\x10\xf4\a\x12\x11\n" +
	"\fHealthStatus\x10\xf5\a\x12\x0e\n" +
	"\tErrorCode\x10\xf6\a\x12\x0e\n" +
	"\tTimestamp\x10\xf7\a\x12\x12\n" +
	"\rTraceHopCount\x10\xf8\a\x12\x11\n" +
	"\fTraceHopType\x10\xf9\a\x12\x0f\n" +
	"\n" +
	"TraceHopId\x10\xfa\a\x12\x19\n" +
	"\x14TraceSourceRequestId\x10\xfb\a\x12\x0f\n" +
	"\n" +
	"TraceError\x10\xfc\a\x12\x0f\n" +
	"\n" +
	"ListenerId\x10\xfd\a\x12\r\n" +
	"\bConnType\x10\xfe\a\x12\x14\n" +
	"\x0fSupportsInspect\x10\xff\a\x12\x18\n" +
	"\x13SupportsBindSuccess\x10\x80\b\x12\x15\n" +
	"\x10ConnectionMarker\x10\x81\b\x12\x0e\n" +
	"\tCircuitId\x10\x82\b\x12\x14\n" +
	"\x0fStickinessToken\x10\x83\b\x12\x13\n" +
	"\x0eUseXgressToSdk\x10\x84\b\x12\x11\n" +
	"\fXgressCtrlId\x10\x85\b\x12\x12\n" +
	"\rXgressAddress\x10\x86\b\x12\x1b\n" +
	"\x16InspectRequestedValues\x10\x87\b\x12\x1a\n" +
	"\x15SupportsPostureChecks\x10\x88\b\x12\x14\n" +
	"\x0fStructuredError\x10\x89\b\x12\x15\n" +
	"\x10DialerIdentityId\x10\x8a\b\x12\x17\n" +
	"\x12DialerIdentityName\x10\x8b\b\x12\x0e\n" +
	"\tServiceId\x10\x8c\b\x12\x1a\n" +
	"\x15ServiceIdentifierType\x10\x8d\b\x12\x15\n" +
	"\x10ConnectRequestId\x10\x8e\b\x12\x17\n" +
	"\x12RouterCapabilities\x10\x8f\b*\xca\x02\n" +
	"\x05Error\x12\x06\n" +
	"\x02OK\x10\x00\x12\f\n" +
	"\bInternal\x10\x01\x12\x15\n" +
	"\x11InvalidApiSession\x10\x02\x12\x12\n" +
	"\x0eInvalidSession\x10\x03\x12\x14\n" +
	"\x10WrongSessionType\x10\x04\x12\x1f\n" +
	"\x1bInvalidEdgeRouterForSession\x10\x05\x12\x12\n" +
	"\x0eInvalidService\x10\x06\x12\x17\n" +
	"\x13TunnelingNotEnabled\x10\a\x12\x15\n" +
	"\x11InvalidTerminator\x10\b\x12\x15\n" +
	"\x11InvalidPrecedence\x10\t\x12\x0f\n" +
	"\vInvalidCost\x10\n" +
	"\x12\x19\n" +
	"\x15EncryptionDataMissing\x10\v\x12\x19\n" +
	"\x15InvalidApiSessionType\x10\f\x12\x15\n" +
	"\x11InvalidInstanceId\x10\r\x12\x10\n" +
	"\fAccessDenied\x10\x0e*8\n" +
	"\x0fPrecedenceValue\x12\v\n" +
	"\aDefault\x10\x00\x12\f\n" +
	"\bRequired\x10\x01\x12\n" +
	"\n" +
	"\x06Failed\x10\x02*W\n" +
	"\x04Flag\x12\b\n" +
	"\x04ZERO\x10\x00\x12\a\n" +
	"\x03FIN\x10\x01\x12\x0e\n" +
	"\n" +
	"TRACE_UUID\x10\x02\x12\r\n" +
	"\tMULTIPART\x10\x04\x12\n" +
	"\n" +
	"\x06STREAM\x10\b\x12\x11\n" +
	"\rMULTIPART_MSG\x10\x10BK\n" +
	"\x17org.openziti.edge.protoZ0github.com/openziti/sdk-golang/pb/edge_client_pbb\x06proto3"

var (
	file_edge_client_proto_rawDescOnce sync.Once
	file_edge_client_proto_rawDescData []byte
)

func file_edge_client_proto_rawDescGZIP() []byte {
	file_edge_client_proto_rawDescOnce.Do(func() {
		file_edge_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_client_proto_rawDesc), len(file_edge_client_proto_rawDesc)))
	})
	return file_edge_client_proto_rawDescData
}

var file_edge_client_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_edge_client_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_edge_client_proto_goTypes = []any{
	(ContentType)(0),                        // 0: ziti.edge_client.pb.ContentType
	(HeaderId)(0),                           // 1: ziti.edge_client.pb.HeaderId
	(Error)(0),                              // 2: ziti.edge_client.pb.Error
	(PrecedenceValue)(0),                    // 3: ziti.edge_client.pb.PrecedenceValue
	(Flag)(0),                               // 4: ziti.edge_client.pb.Flag
	(*ServicePostureStateRequest)(nil),      // 5: ziti.edge_client.pb.ServicePostureStateRequest
	(*ServicePostureStateResponse)(nil),     // 6: ziti.edge_client.pb.ServicePostureStateResponse
	(*ServicePostureState)(nil),             // 7: ziti.edge_client.pb.ServicePostureState
	(*Policy)(nil),                          // 8: ziti.edge_client.pb.Policy
	(*PostureQuery)(nil),                    // 9: ziti.edge_client.pb.PostureQuery
	(*PostureResponses)(nil),                // 10: ziti.edge_client.pb.PostureResponses
	(*PostureResponse)(nil),                 // 11: ziti.edge_client.pb.PostureResponse
	nil,                                     // 12: ziti.edge_client.pb.ServicePostureStateResponse.StatesEntry
	nil,                                     // 13: ziti.edge_client.pb.ServicePostureState.PoliciesEntry
	nil,                                     // 14: ziti.edge_client.pb.Policy.PostureQueriesEntry
	(*PostureQuery_Processes)(nil),          // 15: ziti.edge_client.pb.PostureQuery.Processes
	(*PostureQuery_Process)(nil),            // 16: ziti.edge_client.pb.PostureQuery.Process
	(*PostureResponse_TotpToken)(nil),       // 17: ziti.edge_client.pb.PostureResponse.TotpToken
	(*PostureResponse_Macs)(nil),            // 18: ziti.edge_client.pb.PostureResponse.Macs
	(*PostureResponse_OperatingSystem)(nil), // 19: ziti.edge_client.pb.PostureResponse.OperatingSystem
	(*PostureResponse_Domain)(nil),          // 20: ziti.edge_client.pb.PostureResponse.Domain
	(*PostureResponse_Process)(nil),         // 21: ziti.edge_client.pb.PostureResponse.Process
	(*PostureResponse_ProcessList)(nil),     // 22: ziti.edge_client.pb.PostureResponse.ProcessList
	(*PostureResponse_Woken)(nil),           // 23: ziti.edge_client.pb.PostureResponse.Woken
	(*PostureResponse_Unlocked)(nil),        // 24: ziti.edge_client.pb.PostureResponse.Unlocked
	(*PostureResponse_SdkInfo)(nil),         // 25: ziti.edge_client.pb.PostureResponse.SdkInfo
	(*timestamppb.Timestamp)(nil),           // 26: google.protobuf.Timestamp
}
var file_edge_client_proto_depIdxs = []int32{
	12, // 0: ziti.edge_client.pb.ServicePostureStateResponse.states:type_name -> ziti.edge_client.pb.ServicePostureStateResponse.StatesEntry
	13, // 1: ziti.edge_client.pb.ServicePostureState.policies:type_name -> ziti.edge_client.pb.ServicePostureState.PoliciesEntry
	14, // 2: ziti.edge_client.pb.Policy.postureQueries:type_name -> ziti.edge_client.pb.Policy.PostureQueriesEntry
	26, // 3: ziti.edge_client.pb.PostureQuery.timeoutAt:type_name -> google.protobuf.Timestamp
	15, // 4: ziti.edge_client.pb.PostureQuery.processes:type_name -> ziti.edge_client.pb.PostureQuery.Processes
	11, // 5: ziti.edge_client.pb.PostureResponses.responses:type_name -> ziti.edge_client.pb.PostureResponse
	18, // 6: ziti.edge_client.pb.PostureResponse.macs:type_name -> ziti.edge_client.pb.PostureResponse.Macs
	19, // 7: ziti.edge_client.pb.PostureResponse.os:type_name -> ziti.edge_client.pb.PostureResponse.OperatingSystem
	22, // 8: ziti.edge_client.pb.PostureResponse.processList:type_name -> ziti.edge_client.pb.PostureResponse.ProcessList
	20, // 9: ziti.edge_client.pb.PostureResponse.domain:type_name -> ziti.edge_client.pb.PostureResponse.Domain
	23, // 10: ziti.edge_client.pb.PostureResponse.woken:type_name -> ziti.edge_client.pb.PostureResponse.Woken
	24, // 11: ziti.edge_client.pb.PostureResponse.unlocked:type_name -> ziti.edge_client.pb.PostureResponse.Unlocked
	25, // 12: ziti.edge_client.pb.PostureResponse.sdkInfo:type_name -> ziti.edge_client.pb.PostureResponse.SdkInfo
	17, // 13: ziti.edge_client.pb.PostureResponse.totpToken:type_name -> ziti.edge_client.pb.PostureResponse.TotpToken
	7,  // 14: ziti.edge_client.pb.ServicePostureStateResponse.StatesEntry.value:type_name -> ziti.edge_client.pb.ServicePostureState
	8,  // 15: ziti.edge_client.pb.ServicePostureState.PoliciesEntry.value:type_name -> ziti.edge_client.pb.Policy
	9,  // 16: ziti.edge_client.pb.Policy.PostureQueriesEntry.value:type_name -> ziti.edge_client.pb.PostureQuery
	16, // 17: ziti.edge_client.pb.PostureQuery.Processes.processes:type_name -> ziti.edge_client.pb.PostureQuery.Process
	21, // 18: ziti.edge_client.pb.PostureResponse.ProcessList.processes:type_name -> ziti.edge_client.pb.PostureResponse.Process
	26, // 19: ziti.edge_client.pb.PostureResponse.Woken.Time:type_name -> google.protobuf.Timestamp
	26, // 20: ziti.edge_client.pb.PostureResponse.Unlocked.Time:type_name -> google.protobuf.Timestamp
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_edge_client_proto_init() }
func file_edge_client_proto_init() {
	if File_edge_client_proto != nil {
		return
	}
	file_edge_client_proto_msgTypes[6].OneofWrappers = []any{
		(*PostureResponse_Macs_)(nil),
		(*PostureResponse_Os)(nil),
		(*PostureResponse_ProcessList_)(nil),
		(*PostureResponse_Domain_)(nil),
		(*PostureResponse_Woken_)(nil),
		(*PostureResponse_Unlocked_)(nil),
		(*PostureResponse_SdkInfo_)(nil),
		(*PostureResponse_TotpToken_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_client_proto_rawDesc), len(file_edge_client_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edge_client_proto_goTypes,
		DependencyIndexes: file_edge_client_proto_depIdxs,
		EnumInfos:         file_edge_client_proto_enumTypes,
		MessageInfos:      file_edge_client_proto_msgTypes,
	}.Build()
	File_edge_client_proto = out.File
	file_edge_client_proto_goTypes = nil
	file_edge_client_proto_depIdxs = nil
}
