name: build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install Ziti CI
        uses: openziti/ziti-ci@v1

      - name: Build and Test
        run: |
          go test ./...
          go test -C example ./...
          go install ./...

      - name: Check license
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./license-check.sh
          $(go env GOPATH)/bin/ziti-ci verify-version $($(go env GOPATH)/bin/sdk-version)
