name: mattermost-ziti-webhook
on:
  issues:
  issue_comment:
  pull_request_review:
    types: [ submitted ]
  pull_request_review_comment:
  pull_request:
    types: [ opened, reopened, ready_for_review, closed ]
  fork:
  push:
    tags:
      - '*'
  release:
    types: [ released ]
  workflow_dispatch:
  watch:
    types: [ started ]

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    name: POST Webhook
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: openziti/ziti-mattermost-action-py@main
        if: |
          github.repository_owner == 'openziti'
          && ((github.event_name != 'pull_request_review')
          || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved'))
        with:
          zitiId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
          webhookUrl: ${{ secrets.ZHOOK_URL_DEV_NOTIFICATIONS }}
          eventJson: ${{ toJson(github.event) }}
          senderUsername: "GitHubZ"
          destChannel: "dev-notifications"

      - uses: openziti/ziti-mattermost-action-py@main
        if: |
          github.repository_owner == 'openziti'
          && ((github.event_name != 'pull_request_review')
          || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved'))
        with:
          zitiId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
          webhookUrl: ${{ secrets.ZHOOK_URL_GITHUB_SIG_CORE }}
          eventJson: ${{ toJson(github.event) }}
          senderUsername: "GitHubZ"
          destChannel: "github-sig-core"

